Fix: migrate from no longer lxml supported XPath.evaluate(node) to XPath as callable
Exirel/python-xmlunittest pull request #15
Opened 2024-06-25 01:32 UTC by mezka

XPath.evaluate is no longer in `lxml`, now the XPath expression is callable directly.

First, thank you very much for making this project. I am actually not familiar with it, but I'm trying to fix  [InvoiceGenerator](https://pypi.org/project/InvoiceGenerator/) which I'm actually not that familiar with as well, but I'm trying to fix it and then use it.

Please swiftly merge and bump and release pypi package, in order for me to upgrade it in the other project and be able to use it.

Thank you for being a good mantainer.

Kind regards.

2024-06-26 19:53 UTC, Exirel commented on requirements.txt
> +lxml==5.2.2
```suggestion
lxml>=4.0.0
```

As far as I can tell, lxml 4.0 support the XPath callable object instead of the `evaluate` method, and I don't see the necessity to force that specific version of lxml here.

2024-06-26 19:54 UTC, Exirel requested changes
Before I can merge that, I'd like to have the lxml minimum version requirement modified to `>=4.0.0` which looks compatible.

2024-07-02 10:32 UTC, mezka commented
Ready to merge?

2024-07-11 08:35 UTC, Exirel approved these changes

2024-07-11 08:35 UTC, merged